#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "one"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  automatic_update = true
  statusline_separator = "arrow"
  statusline_iseparator = "nil"
  buffer_index_type = 4
  enable_statusline_mode = true
  enable_statusline_tag = true
  enable_tabline_filetype_icon = true
  statusline_right_sections = [
    'fileformat',
    'cursorpos',
    'percentage'
  ]
  filemanager = "nerdtree"
  guifont = "DejaVu Sans Mono for Powerline 10"
  bootstrap_before = 'myspacevim#before'

[[layers]]
    name = 'core'
    filetree_show_hidden = true

[[layers]]
  name = 'autocomplete'
  autocomplete_method = "coc"
  snippet_engine = "ultisnips"
  auto_completion_return_key_behavior = "nil"
  auto_completion_tab_key_behavior = "complete"
  auto_completion_enable_snippets_in_popup = false

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "checkers"
  lint_on_the_fly = true

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "default"

[[layers]]
  name = "edit"
  textobj = [
    'indent',
    'line',
    'entire'
  ]

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  clang_executable = "/usr/bin/clang"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#python"
  python_file_head = [
       '#!/usr/bin/env python',
       '# -*- coding: utf-8 -*-',
        '',
        ''
    ]

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "sudo"

[[layers]]
  name = "lsp"

